In [2]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('Francia.csv')
data.head(5)

,Unnamed: 0,name,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,...,review_scores_cleanliness,review_scores_checkin,review_scores_location,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_entire_homes.1,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,"Duplex avec vue, centre ville",269557,Isabelle,2010-10-24,"Lyon, France",I'm 47 years old. I enjoy books and arts. I'm ...,within a few hours,1.0,f,...,4.71,4.78,4.86,"Available with a mobility lease only (""bail mo...",f,1,1,1,0,0.33
1,1,Nice Flat in the center of Lyon,411285,Clementine,2011-02-26,"Lyon, France",Je travaille dans le cinéma et je voyage beauc...,within an hour,1.0,f,...,4.80,4.96,4.88,6938113058353,f,1,1,1,0,0.15
2,2,"Centre of old town,home sweet home",660135,Polali,2011-06-03,"Lyon, France","J'ai 34 ans , je suis animatrice auprès de per...",a few days or more,0.0,f,...,4.27,4.72,4.86,6938513221658,f,1,1,1,0,0.82
3,3,"Bel apartment, 2 rooms, Lyon center",670404,Sandrine,2011-06-06,"Lyon, France","We are a family with 3 daughters, aged 16-14-1...",NaN,NaN,f,...,4.89,4.89,4.95,693861800177,f,1,1,1,0,0.12
4,4,Quartier Terreaux 4/6 pers. Hyper centre / Clim,832917,Giuseppina,2011-07-18,"Rhône-Alpes, France","Mon pays d'origine est l'Italie, mais je résid...",within an hour,1.0,f,...,4.86,4.83,4.88,6938112368465,f,2,2,2,0,2.99

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9891 entries, 0 to 9890
Data columns (total 51 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Unnamed: 0                                     9891 non-null   int64
 1   name                                           9891 non-null   object
 2   host_id                                        9891 non-null   int64
 3   host_name                                      9889 non-null   object
 4   host_since                                     9889 non-null   object
 5   host_location                                  8367 non-null   object
 6   host_about                                     3825 non-null   object
 7   host_response_time                             5235 non-null   object
 8   host_response_rate                             5235 non-null   float64
 9   host_is_superhost                              9680 non-null   object
 10  host_neighbourhood                             4347 non-null   object
 11  host_listings_count                            9889 non-null   float64
 12  host_total_listings_count                      9889 non-null   float64
 13  host_identity_verified                         9889 non-null   object
 14  neighbourhood_cleansed                         9891 non-null   object
 15  latitude                                       9891 non-null   float64
 16  longitude                                      9891 non-null   float64
 17  property_type                                  9891 non-null   object
 18  room_type                                      9891 non-null   object
 19  accommodates                                   9891 non-null   int64
 20  bathrooms                                      5466 non-null   float64
 21  bedrooms                                       8519 non-null   float64
 22  beds                                           5458 non-null   float64
 23  price                                          5470 non-null   float64
 24  minimum_nights                                 9891 non-null   int64
 25  maximum_nights                                 9891 non-null   int64
 26  minimum_minimum_nights                         9891 non-null   int64
 27  maximum_minimum_nights                         9891 non-null   int64
 28  minimum_maximum_nights                         9891 non-null   int64
 29  maximum_maximum_nights                         9891 non-null   int64
 30  minimum_nights_avg_ntm                         9891 non-null   float64
 31  maximum_nights_avg_ntm                         9891 non-null   float64
 32  availability_30                                9891 non-null   int64
 33  availability_60                                9891 non-null   int64
 34  availability_90                                9891 non-null   int64
 35  availability_365                               9891 non-null   int64
 36  number_of_reviews                              9891 non-null   int64
 37  number_of_reviews_ltm                          9891 non-null   int64
 38  number_of_reviews_l30d                         9891 non-null   int64
 39  last_review                                    8024 non-null   object
 40  review_scores_rating                           8024 non-null   float64
 41  review_scores_cleanliness                      8024 non-null   float64
 42  review_scores_checkin                          8021 non-null   float64
 43  review_scores_location                         8020 non-null   float64
 44  license                                        5916 non-null   object
 45  instant_bookable                               9891 non-null   object
 46  calculated_host_listings_count                 9891 non-null   int64
 47  calculated_host_listings_count_entire_homes    9891 non-null   int64
 48  calculated_host_listings_count_entire_homes.1  9891 non-null   int64
 49  calculated_host_listings_count_shared_rooms    9891 non-null   int64
 50  reviews_per_month                              8024 non-null   float64
dtypes: float64(16), int64(20), object(15)
memory usage: 3.8+ MB

In [5]:
#Asignamos el nombre "dataframe" a nuestra base de datos
dataframe=data

In [6]:
dataframe2=data

In [7]:
dataframe3=data

In [8]:
dataframe4=data

In [9]:
dataframe5=data

***Función para identificar valores nulos***

In [10]:
def valores_nulos(dataframe):
    #Valores nulos por columna
    valores_nulos_cols = dataframe.isnull().sum()
    #Valores nulos por dataframe
    valores_nulos_df = dataframe.isnull().sum().sum()
    
    return("Valores nulos por columna", valores_nulos_cols,
            "Valores nulos por dataframe", valores_nulos_df)

In [11]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
valores_nulos(dataframe)

('Valores nulos por columna',
 Unnamed: 0                                          0
 name                                                0
 host_id                                             0
 host_name                                           2
 host_since                                          2
 host_location                                    1524
 host_about                                       6066
 host_response_time                               4656
 host_response_rate                               4656
 host_is_superhost                                 211
 host_neighbourhood                               5544
 host_listings_count                                 2
 host_total_listings_count                           2
 host_identity_verified                              2
 neighbourhood_cleansed                              0
 latitude                                            0
 longitude                                           0
 property_type                                       0
 room_type                                           0
 accommodates                                        0
 bathrooms                                        4425
 bedrooms                                         1372
 beds                                             4433
 price                                            4421
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 minimum_nights_avg_ntm                              0
 maximum_nights_avg_ntm                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 last_review                                      1867
 review_scores_rating                             1867
 review_scores_cleanliness                        1867
 review_scores_checkin                            1870
 review_scores_location                           1871
 license                                          3975
 instant_bookable                                    0
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_entire_homes.1       0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                                1867
 dtype: int64,
 'Valores nulos por dataframe',
 np.int64(52502))

**Primer reemplazo: valores nulos con el método mediana para columnas tipo numeric**

In [12]:
def sustitución_mediana(dataframe):
    #Separo columnas cuantitativas del dataframe
    cuantitativas_con_nulos = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas = dataframe.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cuantitativas = cuantitativas_con_nulos.fillna(round(cuantitativas_con_nulos.median(), 1))
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [13]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
dataframe_sin_nulos= sustitución_mediana(dataframe)
dataframe_sin_nulos

,Unnamed: 0,host_id,host_response_rate,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,...,host_response_time,host_is_superhost,host_neighbourhood,host_identity_verified,neighbourhood_cleansed,property_type,room_type,last_review,license,instant_bookable
0,0,269557,1.00,1.0,3.0,45.763140,4.829760,5,2.5,3.0,...,within a few hours,f,5th Arrondissement,t,5e Arrondissement,Entire rental unit,Entire home/apt,2024-06-30,"Available with a mobility lease only (""bail mo...",f
1,1,411285,1.00,1.0,1.0,45.768420,4.827450,4,1.0,1.0,...,within an hour,f,NaN,t,1er Arrondissement,Entire rental unit,Entire home/apt,2024-12-08,6938113058353,f
2,2,660135,0.00,1.0,2.0,45.759300,4.825480,2,1.0,1.0,...,a few days or more,f,5th Arrondissement,t,5e Arrondissement,Entire rental unit,Entire home/apt,2024-06-04,6938513221658,f
3,3,670404,1.00,1.0,1.0,45.768845,4.854162,2,1.0,1.0,...,NaN,f,NaN,t,6e Arrondissement,Entire condo,Entire home/apt,2019-12-28,693861800177,f
4,4,832917,1.00,5.0,5.0,45.766950,4.832410,6,1.0,3.0,...,within an hour,f,1st Arrondissement,t,1er Arrondissement,Entire rental unit,Entire home/apt,2024-11-24,6938112368465,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9886,9886,651608878,0.87,27.0,29.0,45.747560,4.849059,5,2.0,2.0,...,within an hour,f,NaN,t,7e Arrondissement,Entire rental unit,Entire home/apt,NaN,6900078928345,t
9887,9887,651608878,0.87,27.0,29.0,45.757020,4.844830,6,1.0,2.0,...,within an hour,f,NaN,t,3e Arrondissement,Entire rental unit,Entire home/apt,NaN,6900399034456,t
9888,9888,666633599,1.00,1.0,1.0,45.737954,4.840085,2,1.0,1.0,...,NaN,f,NaN,t,7e Arrondissement,Entire rental unit,Entire home/apt,NaN,6938712751252,f
9889,9889,12466813,1.00,1.0,2.0,45.744800,4.831920,4,1.0,2.0,...,within an hour,f,NaN,t,7e Arrondissement,Entire rental unit,Entire home/apt,NaN,6938713431341,f
9890,9890,417340177,1.00,20.0,39.0,45.766985,4.837964,2,1.0,1.0,...,within an hour,NaN,NaN,t,1er Arrondissement,Entire rental unit,Entire home/apt,NaN,Exempt - hotel-type listing,t

In [14]:
valores_nulos(dataframe_sin_nulos)

('Valores nulos por columna',
 Unnamed: 0                                          0
 host_id                                             0
 host_response_rate                                  0
 host_listings_count                                 0
 host_total_listings_count                           0
 latitude                                            0
 longitude                                           0
 accommodates                                        0
 bathrooms                                           0
 bedrooms                                            0
 beds                                                0
 price                                               0
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 minimum_nights_avg_ntm                              0
 maximum_nights_avg_ntm                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 review_scores_rating                                0
 review_scores_cleanliness                           0
 review_scores_checkin                               0
 review_scores_location                              0
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_entire_homes.1       0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                                   0
 name                                                0
 host_name                                           2
 host_since                                          2
 host_location                                    1524
 host_about                                       6066
 host_response_time                               4656
 host_is_superhost                                 211
 host_neighbourhood                               5544
 host_identity_verified                              2
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 last_review                                      1867
 license                                          3975
 instant_bookable                                    0
 dtype: int64,
 'Valores nulos por dataframe',
 np.int64(23849))

In [15]:
#Converti DF a CSV
dataframe_sin_nulos.to_csv('01_mediana.csv')

**Segundo ejercicio: método de "ffill" en columnas tipo object, datetime y category**

In [16]:
def sustitución_ffill(dataframe2):
    #Separo columnas cuantitativas del dataframe
    cuantitativas = dataframe2.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas = dataframe2.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cualitativas = cualitativas.fillna(method="ffill")
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [17]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
dataframe_sin_nulos1= sustitución_ffill(dataframe2)
dataframe_sin_nulos1
valores_nulos(dataframe_sin_nulos1)

/var/folders/vk/htzm_z194jz4tflq2s4s86x80000gn/T/ipykernel_4238/3674674741.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cualitativas = cualitativas.fillna(method="ffill")

('Valores nulos por columna',
 Unnamed: 0                                          0
 host_id                                             0
 host_response_rate                               4656
 host_listings_count                                 2
 host_total_listings_count                           2
 latitude                                            0
 longitude                                           0
 accommodates                                        0
 bathrooms                                        4425
 bedrooms                                         1372
 beds                                             4433
 price                                            4421
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 minimum_nights_avg_ntm                              0
 maximum_nights_avg_ntm                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 review_scores_rating                             1867
 review_scores_cleanliness                        1867
 review_scores_checkin                            1870
 review_scores_location                           1871
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_entire_homes.1       0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                                1867
 name                                                0
 host_name                                           0
 host_since                                          0
 host_location                                       0
 host_about                                          0
 host_response_time                                  0
 host_is_superhost                                   0
 host_neighbourhood                                  0
 host_identity_verified                              0
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 last_review                                         0
 license                                             0
 instant_bookable                                    0
 dtype: int64,
 'Valores nulos por dataframe',
 np.int64(28653))

In [28]:
#Converti DF a CSV
dataframe_sin_nulos1.to_csv('02_ffill.csv')

**Tercer ejercicio: método "bfill" para tipo object, datetime y category**

In [18]:
def sustitución_bfill(dataframe3):
    #Separo columnas cuantitativas del dataframe
    cuantitativas = dataframe3.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas = dataframe3.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cualitativas = cualitativas.fillna(method="bfill")
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [19]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
dataframe_sin_nulos2= sustitución_ffill(dataframe3)
dataframe_sin_nulos2
valores_nulos(dataframe_sin_nulos2)

/var/folders/vk/htzm_z194jz4tflq2s4s86x80000gn/T/ipykernel_4238/3674674741.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cualitativas = cualitativas.fillna(method="ffill")

('Valores nulos por columna',
 Unnamed: 0                                          0
 host_id                                             0
 host_response_rate                               4656
 host_listings_count                                 2
 host_total_listings_count                           2
 latitude                                            0
 longitude                                           0
 accommodates                                        0
 bathrooms                                        4425
 bedrooms                                         1372
 beds                                             4433
 price                                            4421
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 minimum_nights_avg_ntm                              0
 maximum_nights_avg_ntm                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 review_scores_rating                             1867
 review_scores_cleanliness                        1867
 review_scores_checkin                            1870
 review_scores_location                           1871
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_entire_homes.1       0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                                1867
 name                                                0
 host_name                                           0
 host_since                                          0
 host_location                                       0
 host_about                                          0
 host_response_time                                  0
 host_is_superhost                                   0
 host_neighbourhood                                  0
 host_identity_verified                              0
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 last_review                                         0
 license                                             0
 instant_bookable                                    0
 dtype: int64,
 'Valores nulos por dataframe',
 np.int64(28653))

In [29]:
#Converti DF a CSV
dataframe_sin_nulos2.to_csv('03_bfill.csv')

**Cuarto ejercicio con el método "string concreto" en columnas tipo object, datetime y category**

In [20]:
def sustitución_string_concreto(dataframe4):
    #Separo columnas cuantitativas del dataframe
    cuantitativas = dataframe3.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas = dataframe3.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cualitativas = cualitativas.fillna('Sin datos')
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [21]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
dataframe_sin_nulos3= sustitución_string_concreto(dataframe4)
dataframe_sin_nulos3
valores_nulos(dataframe_sin_nulos3)

('Valores nulos por columna',
 Unnamed: 0                                          0
 host_id                                             0
 host_response_rate                               4656
 host_listings_count                                 2
 host_total_listings_count                           2
 latitude                                            0
 longitude                                           0
 accommodates                                        0
 bathrooms                                        4425
 bedrooms                                         1372
 beds                                             4433
 price                                            4421
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 minimum_nights_avg_ntm                              0
 maximum_nights_avg_ntm                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 review_scores_rating                             1867
 review_scores_cleanliness                        1867
 review_scores_checkin                            1870
 review_scores_location                           1871
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_entire_homes.1       0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                                1867
 name                                                0
 host_name                                           0
 host_since                                          0
 host_location                                       0
 host_about                                          0
 host_response_time                                  0
 host_is_superhost                                   0
 host_neighbourhood                                  0
 host_identity_verified                              0
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 last_review                                         0
 license                                             0
 instant_bookable                                    0
 dtype: int64,
 'Valores nulos por dataframe',
 np.int64(28653))

In [30]:
#Converti DF a CSV
dataframe_sin_nulos3.to_csv('04_string_sin_nulos.csv')

**Quinto ejercicio con el método de "constante" en columnas tipo numeric**

In [22]:
def constante(dataframe5):
    #Separo columnas cuantitativas del dataframe
    cuantitativas = dataframe3.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas = dataframe3.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cuantitativas = cuantitativas.fillna(50000)
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [23]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
dataframe_sin_nulos4= constante(dataframe5)
dataframe_sin_nulos4
valores_nulos(dataframe_sin_nulos4)

('Valores nulos por columna',
 Unnamed: 0                                          0
 host_id                                             0
 host_response_rate                                  0
 host_listings_count                                 0
 host_total_listings_count                           0
 latitude                                            0
 longitude                                           0
 accommodates                                        0
 bathrooms                                           0
 bedrooms                                            0
 beds                                                0
 price                                               0
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 minimum_nights_avg_ntm                              0
 maximum_nights_avg_ntm                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 review_scores_rating                                0
 review_scores_cleanliness                           0
 review_scores_checkin                               0
 review_scores_location                              0
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_entire_homes.1       0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                                   0
 name                                                0
 host_name                                           2
 host_since                                          2
 host_location                                    1524
 host_about                                       6066
 host_response_time                               4656
 host_is_superhost                                 211
 host_neighbourhood                               5544
 host_identity_verified                              2
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 last_review                                      1867
 license                                          3975
 instant_bookable                                    0
 dtype: int64,
 'Valores nulos por dataframe',
 np.int64(23849))

In [31]:
#Converti DF a CSV
dataframe_sin_nulos4.to_csv('05_constante.csv')